version: 2.1

parameters:
  is_pr:
    type: boolean
    default: false

orbs:
  unity: game-ci/unity@1.4

workflows:
  build-unity-project:
    when: << pipeline.parameters.is_pr >>
    jobs:
      # Linux IL2CPP
      - unity/build:
          name: 'build-linux64-il2cpp'
          step-name: 'Build StandaloneLinux64'
          return-license: true
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'linux-il2cpp'
            editor_version: '2021.3.26f1'
            resource_class: 'large'
          project-path: './'
          build-target: StandaloneLinux64
          compress: true
          context: project-consequences

      # Windows IL2CPP
      - unity/build:
          name: 'build-Windows64-il2cpp'
          step-name: 'Build StandaloneWindows64 il2cpp'
          return-license: true
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2019'
            size: 'large'
            editor_version: '2021.3.26f1'
            target_platform: 'windows-il2cpp'
          project-path: './'
          build-target: StandaloneWindows64
          compress: true
          context: project-consequences

      # # macOS Mono
      # - unity/build:
      #     name: 'build-osx-mono'
      #     step-name: 'Build StandaloneOSX'
      #     unity-serial-var-name: 'UNITY_SERIAL'
      #     unity-username-var-name: 'UNITY_USERNAME'
      #     unity-password-var-name: 'UNITY_PASSWORD'
      #     executor:
      #       name: 'unity/ubuntu'
      #       target_platform: 'mac-mono'
      #       editor_version: '2021.3.2f1'
      #       resource_class: 'large'
      #     project-path: './'
      #     build-target: 'StandaloneOSX'
      #     context: project-consequences
