version: 2.1

orbs:
  unity: game-ci/unity@1.4

workflows:
  build-unity-project:
    jobs:
      # Linux IL2CPP
      - unity/build:
          name: 'build-linux64-il2cpp'
          step-name: 'Build StandaloneLinux64'
          return-license: true
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'linux-il2cpp'
            editor_version: '2021.3.26f1'
            resource_class: 'large'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          build-target: StandaloneLinux64
          compress: true
          context: project-consequences

      # Windows IL2CPP
      - unity/build:
          name: 'build-Windows64-il2cpp'
          step-name: 'Build StandaloneWindows64 il2cpp'
          return-license: true
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2019'
            size: 'large'
            editor_version: '2021.3.26f1'
            target_platform: 'windows-il2cpp'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          build-target: StandaloneWindows64
          compress: true
          context: project-consequences

      # macOS IL2CPP
      - unity/build:
          name: 'build-osx-il2cpp'
          step-name: 'Build macOS IL2CPP'
          return-license: true
          unity-serial-var-name: 'UNITY_SERIAL'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/macos'
            resource_class: 'large'
            editor_version: '2021.3.26f1'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          build-target: StandaloneOSX
          compress: true
          context: project-consequences